---

###
### Lints all generic and json files in the whole git repository
###

name: building
on:
  pull_request:
  push:
    branches:
      - master
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        version:
          - '2.7'
          - '3.6'
          - '3.7'
          - '3.8'

    name: "[${{ matrix.version }}]"
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Make build
        run: |
          make build VERSION=${version}
        env:
          version: ${{ matrix.version }}

      - name: Make dist
        run: |
          make dist VERSION=${version}
        env:
          version: ${{ matrix.version }}
