---

###
### Lints all generic and json files in the whole git repository
###

name: linting
on:
  pull_request:
  push:
    branches:
      - master
    tags:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        target:
          - Linting
    name: "[ ${{ matrix.target }} ]"
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Lint files
        run: |
          make lint-files

      - name: Python Black
        run: |
          make black

      - name: PyCodeStyle
        run: |
          make pycodestyle

      - name: PyDocStyle
        run: |
          make pydocstyle

      - name: Check consistent version
        run: |
          make version

      - name: Check consistent Usage in Readme
        run: |
          make lint-usage

      - name: Check up-to-date man page
        run: |
          make lint-man

      - name: Check up-to-date docs
        run: |
          make lint-docs
