---

name: testing
on:
  pull_request:
  push:
    branches:
      - master
    tags:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: False
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version:
          - 2.7
          - 3.6
          - 3.7
          - 3.8
        target:
          - test

    name: "[${{ matrix.os }} [${{ matrix.version}}] ${{ matrix.target }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test
        run: |
          make ${target} VERSION=${version}
        env:
          target: ${{ matrix.target }}
          version: ${{ matrix.version }}
