---

name: MacOS
on:
  pull_request:
  push:
    branches:
      - master
    tags:

jobs:
  test:
    runs-on: macos-latest
    strategy:
      fail-fast: False
      matrix:
        version:
          - 2.7
          - 3.6
          - 3.7
          - 3.8
        target:
          - test

    name: "[${{ matrix.version}}] ${{ matrix.target }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.version }}
      - name: Test
        shell: bash
        run: |
          make ${target}
        env:
          target: ${{ matrix.target }}
          version: ${{ matrix.version }}
